### ISSUE TITLE
Collect contributor details, get ORCID iD and add to DESCRIPTION file

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/durbanplasticwaste#3]
@raulalexb, can you please collect the details of everyone contributing to this dataset? Next to you and Chiara, who else has contributed to this data.

Please motivate those contributors to get an ORCID iD. This will enable the publication to be linked to the contributors' names and citations to be attributed.

https://orcid.org/

If there are more than 5 additional contributors, please let me know and we can discuss.

To add the details, open the DESCRIPTION file and edit. You can try it yourself, and copy/paste an entry if there aren't enough. Have a go at it, there is nothing that could be messed up.

https://github.com/Global-Health-Engineering/durbanplasticwaste22/blob/main/DESCRIPTION

**Comment by raulalexb** [comment]
Hi @larnsce,

Just to clarify, who counts as a contributor? Because for my thesis, only Chiara and I were on the field. But we used the materials of Siphiwe and his locations and litter booms. For Chiara's data, the collection was done together with Sfiso, who helped sort through the waste. 
Who should be mentioned? Are Marc and Liz also mentioned? Thanks for the clarification :)

**Comment by larnsce** [comment]
You have just clarified yourself. Yes, everybody should be mentioned. 

- Siphiwe
- Sfiso
- Liz
- Marc

**Comment by raulalexb** [comment]
Okay! I'll get to it, but it might take a while for Siphiwe and Sfiso to get an ORCID account.

**Comment by raulalexb** [comment]
In this case there are 6 contributors, let me know what still has to be discussed ;)

**Comment by larnsce** [comment]
Thanks, Raúl. That should work out.

**Comment by raulalexb** [comment]
@larnsce I would also add Lin, and how about you? You are helping with all the data

**Comment by larnsce** [comment]
Yes, of course. Please add @linboynton. I have already added myself. :)

I am adding myself as the "maintainer" (cre), which means that I will keep this package up to date and running.
You and Chiaran will be "authors" (aut), because of significant contributions.
Siphiwe, Sfiso, Lin, Liz, and Marc will be listed as (ctb), contributors.

I am considering to add the Global Health Engineering group as the funder (fnd).

You can learn more about these categories here: https://r-pkgs.org/description.html#author-who-are-you

**Comment by raulalexb** [comment]
Thanks! Yes, in that case it makes sense to add GHE as a funder ;)

**Comment by larnsce** [comment]
@raulalexb, have you heard back from Siphiwe and Sfiso? I am going to present our new openwashdata project at a conference tomorrow, and I would like to include your data package as an example. 

To do that, I am going to get the final steps done:

- Get DOI from Zenodo
- Publish a website with the package documentation

It would be great to have their details included.

**Comment by raulalexb** [comment]
Hi @larnsce 
I have today! I tried helping him, he says that he gets an error message when he tries it. I am still working on it with him, the communication between us takes long... 

Do you need anything else from me for the conference tomorrow? I will try to call Siphiwe tonight to figure this out.

All the best and I hope it goes well!!

Raúl

**Comment by raulalexb** [comment]
Hi @larnsce,
I have been able to contact Siphiwe, but we can only sit down together and find a solution around lunch. Sfiso sadly doesn't have an email address. Is this still in time for your conference?

**Comment by larnsce** [comment]
Hi @raulalexb. Yes, that's all fine. Thank you. I will update the package as the details come in. I had wanted to include them now so that there is already exposure.

We must still add Sfiso's name, though. Does Sfiso have a mobile phone? We could help him get an email address as well.

**Comment by raulalexb** [comment]
Hi @larnsce 
I went ahead and created a gmail for both of them. I just finished creating an ORCID for Siphiwe, I just added it to the file. I'm struggling with Sfiso because he needs to confirm his phone number and that is taking some time... But at least Siphiwe is on now!

Thanks again for your help :)

**Comment by larnsce** [comment]
Thanks for the effort!

**Comment by larnsce** [comment]
@raulalexb: Do you have updates on the ORCID iD for Sfiso?
