### ISSUE TITLE
Work through to do list before publishing

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/durbanplasticwaste#4]
- [x] add license statement to README.rmd
- [x] add citation to README.rmd

**Comment by larnsce** [comment]
@raulalexb: I have made some progress today. Please review the main page ([README](https://github.com/Global-Health-Engineering/durbanplasticwaste22)) and let me know if you are happy with the current layout.

**Comment by larnsce** [comment]
@raulalexb @linboynton @ChiaraMP 

The package is now publicly available from this domain:

https://global-health-engineering.github.io/durbanplasticwaste/

There is still work to do, but I needed the DOI and want to demonstrate a live page in a talk tomorrow.

I hope that's okay with you.

**Comment by raulalexb** [comment]
Hi @larnsce 

I hope you had a nice weekend :) Could we sit down today or tomorrow to discuss how I can work with the data to create graphs using R? That would be amazing, thank you! :) 

All the best and hope to see you soon,

Raúl

**Comment by larnsce** [comment]
Hi @raulalexb. It's so great to hear that you are interested in learning R. That's a longer journey, but I would still be happy to show you a few things.
