### ISSUE TITLE
Fix citation export

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/durbanplasticwaste#9]
Citation currently doesn't display authors.

**Comment by sebastian-loos** [comment]
Hey @larnsce,
I ended up changing all files that have citation information ([`CITATION.cff`](https://github.com/Global-Health-Engineering/durbanplasticwaste/blob/characterization/CITATION.cff), [`DESCRIPTION`](https://github.com/Global-Health-Engineering/durbanplasticwaste/blob/characterization/DESCRIPTION), [`inst/CITATION`](https://github.com/Global-Health-Engineering/durbanplasticwaste/blob/characterization/inst/CITATION), [`citation.bib`](https://github.com/Global-Health-Engineering/durbanplasticwaste/blob/characterization/citation.bib)) In the last commit `citation()` would display the authors information:)

**Comment by sebastian-loos** [comment]
Unfortunately, my computer keeps setting back the environment variable for the language to German and therefore the output messages too. Don't know how to change it without changing the variable on Admin level which I want to avoid...

**Comment by larnsce** [comment]
You can leave the responsiblity of fixing that with me. There are still some problems with how citations are generated. Did you push the commits? :)

**Comment by sebastian-loos** [comment]
I wasn't sure who I had to add as authors for the citation since we decided on only the authors and maintainers, and not the contributors for openwashdata packages. As for now, I just added myself as a ctb but also as an author for the citation, since everybody is shown in this GHE package...

**Comment by sebastian-loos** [comment]
> You can leave the responsiblity of fixing that with me. There are still some problems with how citations are generated. Did you push the commits? :)

I was working on the `characterization` branch. Ready to merge into main I think.
